name: Comment on the Pull Request

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      code-coverage-artifact-name:
        required: true
        type: string
      code-coverage-artifact-path:
        required: true
        type: string
      event-triggered:
        required: true
        type: string

jobs:
  debug-output:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow event
        run: "echo ${{ github.event_name }}"
      - name: Triggering event name
        run: "echo ${{ inputs.event-triggered }}"
      - name: PR number
        run: "echo ${{ inputs.pr-number }}"
      - name: Code Coverage Artifact Name
        run: "echo ${{ inputs.code-coverage-artifact-name }}"        
      - name: Code Coverage Artifact Path
        run: "echo ${{ inputs.code-coverage-artifact-path }}"
  
  comment:
    runs-on: ubuntu-latest

    # Only comment on the PR if this is a PR event
    if: ${{ inputs.event_triggered }} == 'pull_request'

    steps:   
    - name: Get the code coverage results file
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: ""
        name: ${{ inputs.code-coverage-artifact-name }}

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ inputs.pr-number }}
        recreate: true
        path: ${{ inputs.code-coverage-artifact-path }}
